-- 코드를 입력하세요
-- TOTAL_SALES = SUM (A.PRICE * B.AMOUNT)
-- 
SELECT A.PRODUCT_ID, B.PRODUCT_NAME, SUM(B.PRICE * A.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS A
JOIN FOOD_PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE MONTH(A.PRODUCE_DATE) = 5
GROUP BY A.PRODUCT_ID, B.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;
